### ISSUE TITLE
CachedResults never populated when cache = true

### ISSUE THREAD

**Issue by vwbusguy** [realsuayip/autocomplete#1]
Enabling cache doesn't result in less lookup calls.  It appears that the query results are never actually added to CachedResults, so CachedResults stays an empty array:

https://github.com/realsuayip/autocomplete/blob/master/src/autocomplete.js

Ref. https://github.com/matiasdelellis/facerecognition/issues/766

**Comment by realsuayip** [comment]
Hi, could you provide a minimal reproducible example?

I played with the example contained in the repo a little bit, and everything seems to be fine. The `lookup` promise only resolves for lookups with no cache entries. 

Notice that when a lookup returns no results, its cached in a separate array called `emptyResults`. `cachedResults` contains lookups with actual results.

**Comment by vwbusguy** [comment]
I did some more testing and I apologize, this actually does work.  

I'm trying to debug a problem with the faceregnition app (which I do not maintain), which uses this library to autocomplete names for grouping pictures.  

What appears to be happening is that the facerecognition app is instantiating a new Autocomplete instance for each round of pictures instead of re-using the already loaded library, I presume since the input object itself is getting redrawn with each group of pictures.  

When I test this against the same cluster, I do not see repeat API calls when cache = true.

**Comment by vwbusguy** [comment]
Here's the example I'm working with: https://github.com/matiasdelellis/facerecognition/blob/master/src/dialogs.js#L274  (I've set `cache: true` locally on my server in this file where it's instantiated.)

Unfortunately, the input object gets destroyed and recreated each time with a new id.  Perhaps attempting to store/retrieve the cache in [Local/SessionStorage](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage) so that the cache is retained for the page between instantiations (for browsers that support it), would work?

I'm thinking for this to work it would have to be scoped to a page and explicitly turned on by parameter, because this won't be desired if there are multiple inputs on the same page using AutoComplete with different lookup sources.

Or, even more simply, let the user name the cache in the instantiation and use that as the key for the storage set/get.
